<?php

namespace AppBundle\Repository;

/**
 * MorososRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MorososRepository extends \Doctrine\ORM\EntityRepository
{
}
